### ISSUE TITLE
Nameserver check

### ISSUE THREAD

**Issue by Ali1** [mesour/dns-checker#10]
Hi,

Can you use this library to check a domain's authoratitive nameserver (which is different to the returned NS DNS record).

Thank you

Ali

**Comment by mesour** [comment]
@Ali1 Hello,

for example, do you think the subdomain would be ignored in the comparison? Do I understand that correctly?

**Comment by mesour** [comment]
Hello, yes it can:

```
$dnsRecordSet = $checker->getDnsRecordSet('example.com', DNS_NS);
```
